### ISSUE TITLE
Add Support for EIP-1159 overrides in SendTransaction (function override)

### ISSUE THREAD

**Issue by TheGreatAxios** [TheGreatAxios/issues#3]
```[tasklist]
### Tasks
- [ ] Add Function Overrides in Wallets to set EIP-1159 params instead of Type 0 (gas Price)
- [ ] Ensure Optional Legacy is defined
- [ ] Explore adding getFeeData in JsonRpcProvider -> see ethers link below
```

**Comment by TheGreatAxios** [comment]
https://github.com/ethers-io/ethers.js/blob/9e7e7f3e2f2d51019aaa782e6290e079c38332fb/src.ts/providers/abstract-provider.ts#L920

**Comment by 0xRetroDev** [comment]
I think we already have this: 

```cs
        /// <summary>
        /// Estimates gas for a transaction asynchronously.
        /// </summary>
        /// <param name="from">The sender address.</param>
        /// <param name="to">The recipient address.</param>
        /// <param name="data">The transaction data.</param>
        /// <param name="value">The transaction value.</param>
        /// <returns>The estimated gas.</returns>
        public async Task<HexBigInteger> EstimateGas(string from, string to, string data = null, string value = null)
        {
            // Create a TransactionInput object with the specified parameters
            var transactionInput = new TransactionInput
            {
                From = from,
                To = to,
                Data = data
            };

            if (string.IsNullOrEmpty(value))
            {
                transactionInput.Value = new HexBigInteger(0);
            }
            else
            {
#if UNITY_WEBGL
                transactionInput.Value = new HexBigInteger(value);
#elif !UNITY_WEBGL
                string hexValue = Util.Util.ConvertStringToHex(value);
                transactionInput.Value = new HexBigInteger(hexValue);
#endif
            }

            // Estimate gas for the transaction
            return await web3.Eth.TransactionManager.EstimateGasAsync(transactionInput);
        }
        ```

Or is getgas() something else?

**Comment by TheGreatAxios** [comment]
Confirming @nftpixels this is not related to getGas() directly.
This is explicit to transaction types. 
Here is a solid walkthrough of the difference: https://www.quicknode.com/guides/ethereum-development/transactions/how-to-send-transactions-on-ethereum-using-python

Right now, we have constructors that allow for gasPrice and gas (gas limit) to be set. We need to add function overrides that take named parameters that are sufficient for EIP-1559 and then update that from the signer through the JSLIb. Why? 

Type-2 transactions should actually be cheaper and since we do have developers on non SKALE networks this flexibility could help them.

So gas (gas limit) stays, but gasPrice is removed.
You then add 'maxFeePerGas':

max_fee_per_gas, # Maximum amount you’re willing to pay 
maxPriorityFeePerGas: max_priority_fee_per_gas, # Priority fee to include the transaction in the block

These should just be numbers/hex numbers 

We can also develop endpoints/extensions/examples to use 3rd party APIs e.g https://www.blocknative.com/blog/eip-1559-fees
